name: remedio_certeiro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.2
  appwrite: ^17.1.0
  sqflite: ^2.4.1
  fluttertoast: ^8.2.10
  shared_preferences: ^2.4.0
  flutter_local_notifications: ^18.0.1
  audioplayers: ^6.5.0
  flutter_web_auth_2: ^4.1.0
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - 'resources/images/'
